### ISSUE TITLE
Display a "loading map" when the maps is loading

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos-admin-ui#22]

**Comment by diraol** [comment]
@beraldoleal I've tryied for a couple of hours and couldn't implement this loading.

But I've added a message on status bar indication that a map is under load process, and also the loading of the topology will happen after the map load (which improves browser performance because of less concurrence and also avoids messages from each process being overridden).

So, this is a possible solution. If you think it fits, please, close this issue.
